### ISSUE TITLE
Scripts don't work? Problem with jq

### ISSUE THREAD

**Issue by eyewell** [atorman/elfBash#1]
HI Adam,
I have spent a couple hours trying to get the scripts to work on my mac.
I have force CLI and jq as executables with RWX (chmod 777) privileges.
I have created the scripts.
I have updated the OAuth client and secret keys, for a connected app I created.

Every time I run the script, I get errors:
It won't create the .access_token file
and when I manually create the access_token file, I get these errors on the lines that pipe to jq:

code section with errors:
ids=( $(echo ${elfs} | jq -r ".records[].Id") )
eventTypes=( $(echo ${elfs} | jq -r ".records[].EventType") )
logDates=( $(echo ${elfs} | jq -r ".records[].LogDate" | sed 's/'T.*'//' ) )

output:
eyewell-ltm4:Event Monitoring eyewell$ ./ELFcli2.sh
Please enter username (and press ENTER): eyewell@dev2.com
Please enter password (and press ENTER): Please enter instance (e.g. na1) for the loginURL (and press ENTER): na16
Please enter logdate (e.g. Yesterday, Last_Week, Last_n_Days:5) (and press ENTER): Yesterday
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   586    0   393  100   193    563    276 --:--:-- --:--:-- --:--:--   563
(23) Failed writing body
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    88    0    88    0     0    132      0 --:--:-- --:--:-- --:--:--   132
jq: error: Cannot index array with string
jq: error: Cannot index array with string

jq: error: Cannot index array with string

any tips?

**Comment by jcrben** [comment]
I ran into the issue of "(23) Failed writing body" which is generally a curl errror when piping curl to output to jq, but it was fixed when I added the correct filter of "." to jq. So "curl http://hn.algolia.com/api/v1/items/1 | jq" threw that error whereas "curl http://hn.algolia.com/api/v1/items/1 | jq ." gave me what I wanted (pretty-printed json).

**Comment by eyewell** [comment]
I have since made updates and gotten it to work.
